name: PR Preview Deployment

on:
  pull_request:
    types: [opened, synchronize, reopened]
  pull_request_target:
    types: [closed]

jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    if: github.event.action != 'closed'

    env:
      COOLIFY_API_URL: ${{ secrets.COOLIFY_API_URL }}
      COOLIFY_TOKEN: ${{ secrets.COOLIFY_TOKEN }}
      COOLIFY_PROJECT_ID: ${{ secrets.COOLIFY_PROJECT_ID }}
      REGISTRY: registry.serverfrank.de
      PR_NUMBER: ${{ github.event.number }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push PR image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.REGISTRY }}/taskdown:pr-${{ env.PR_NUMBER }}

      - name: Deploy or update preview app in Coolify
        run: |
          set -euo pipefail
          PREVIEW_NAME="taskdown-pr-${PR_NUMBER}"
          IMAGE_TAG="pr-${PR_NUMBER}"
          IMAGE="${REGISTRY}/taskdown:${IMAGE_TAG}"

          echo "Fetching existing dockerimage applications for project..."
          APPS=$(curl -s -H "Authorization: Bearer ${COOLIFY_TOKEN}" \
            "${COOLIFY_API_URL}/api/v1/projects/${COOLIFY_PROJECT_ID}/dockerimage-applications")

          echo "Applications response:"
          echo "$APPS"

          APP_ID=$(echo "$APPS" | jq -r --arg name "$PREVIEW_NAME" '.[] | select(.name==$name) | .id // empty')

          if [ -z "$APP_ID" ]; then
            echo "Creating new Coolify Docker Image Application: $PREVIEW_NAME"
            APP_ID=$(curl -s -X POST "${COOLIFY_API_URL}/api/v1/dockerimage-applications" \
              -H "Authorization: Bearer ${COOLIFY_TOKEN}" \
              -H "Content-Type: application/json" \
              -d "{\"name\":\"${PREVIEW_NAME}\",\"image\":\"${IMAGE}\",\"preview\":true,\"forcePullImage\":true,\"projectId\":\"${COOLIFY_PROJECT_ID}\"}" | jq -r '.id')
          else
            echo "Updating existing Coolify Docker Image Application: $PREVIEW_NAME"
            curl -s -X PATCH "${COOLIFY_API_URL}/api/v1/dockerimage-applications/${APP_ID}" \
              -H "Authorization: Bearer ${COOLIFY_TOKEN}" \
              -H "Content-Type: application/json" \
              -d "{\"image\":\"${IMAGE}\",\"preview\":true,\"forcePullImage\":true}"
          fi

          echo "Trigger deployment for application $APP_ID with tag $IMAGE_TAG"
          curl -s -X POST "${COOLIFY_API_URL}/api/v1/dockerimage-applications/deploy" \
            -H "Authorization: Bearer ${COOLIFY_TOKEN}" \
            -H "Content-Type: application/json" \
            -d "{\"applicationId\":\"${APP_ID}\",\"tag\":\"${IMAGE_TAG}\"}"

      - name: Comment PR with preview URL
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `🚀 Preview deployment created! View it at: https://pr-${context.issue.number}.your-domain.com`
            })

  cleanup-preview:
    runs-on: ubuntu-latest
    if: github.event.action == 'closed'

    env:
      COOLIFY_API_URL: ${{ secrets.COOLIFY_API_URL }}
      COOLIFY_TOKEN: ${{ secrets.COOLIFY_TOKEN }}
      PR_NUMBER: ${{ github.event.number }}

    steps:
      - name: Delete preview app from Coolify
        run: |
          set -euo pipefail
          PREVIEW_NAME="taskdown-pr-${PR_NUMBER}"

          # Fetch app ID to delete
          APPS=$(curl -s -H "Authorization: Bearer ${COOLIFY_TOKEN}" \
            "${COOLIFY_API_URL}/api/v1/projects/${{ secrets.COOLIFY_PROJECT_ID }}/dockerimage-applications")

          APP_ID=$(echo "$APPS" | jq -r --arg name "$PREVIEW_NAME" '.[] | select(.name==$name) | .id // empty')

          if [ -n "$APP_ID" ]; then
            echo "Deleting Coolify Docker Image Application: $PREVIEW_NAME (ID: $APP_ID)"
            curl -s -X DELETE "${COOLIFY_API_URL}/api/v1/dockerimage-applications/${APP_ID}" \
              -H "Authorization: Bearer ${COOLIFY_TOKEN}"
          else
            echo "No Coolify Docker Image Application found for deletion."
          fi

      - name: Comment PR about cleanup
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '🧹 PR preview deployment cleaned up.'
            })
