name: PR Preview Deployment

on:
  pull_request:
    types: [opened, synchronize, reopened]
  pull_request_target:
    types: [closed]

jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    if: github.event.action != 'closed' && false # Disabled by default

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push PR image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: registry.serverfrank.de/taskdown:pr-${{ github.event.number }}

      - name: Create PR deployment in Coolify
        run: |
          # Create a new deployment for this PR
          curl -X POST "${{ secrets.COOLIFY_API_URL }}/api/v1/projects/${{ secrets.COOLIFY_PROJECT_ID }}/services" \
            -H "Authorization: Bearer ${{ secrets.COOLIFY_API_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d '{
              "name": "pr-${{ github.event.number }}",
              "image": "registry.serverfrank.de/taskdown:pr-${{ github.event.number }}",
              "type": "service"
            }'

      - name: Comment PR with preview URL
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '🚀 Preview deployment created! Will be available at: https://pr-' + context.issue.number + '.your-domain.com'
            })

  cleanup-preview:
    runs-on: ubuntu-latest
    if: github.event.action == 'closed' && false # Disabled by default

    steps:
      - name: Delete PR deployment
        run: |
          # Delete the PR deployment from Coolify
          curl -X DELETE "${{ secrets.COOLIFY_API_URL }}/api/v1/services/pr-${{ github.event.number }}" \
            -H "Authorization: Bearer ${{ secrets.COOLIFY_API_TOKEN }}"

      - name: Comment PR about cleanup
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '🧹 PR preview deployment has been cleaned up.'
            })
